import 'package:get/get.dart';

class MultiLanguageModel extends Translations {
  @override
  // TODO: implement keys
  Map<String, Map<String, String>> get keys => {
        "en_US": {
          "Ok": "Ok",
          "Select language": "Select language",
          "Choose Language": "Choose Language",
          "Keyboard": "Keyboard",
          "Recent": "Recent",
          "Schedule": "Schedule",
          "Setting": "Setting",
          "Add Name": "Add name",
          "Add Message": "Add message",
          "Enter Name": "Enter mame",
          "Enter Message": "Enter message",
          "No Recent": "You don't have any recent data",
          "Add Recent": "Add recent data now",
          "No Message": "No message",
          "No Schedule":
              "You haven’t scheduled a message yet. To remind on scheduled time we will send a notification.",
          "Add Schedule": "Schedule Now",
          "Yes": "Yes",
          "No": "No",
          "Cancel": "Cancel",
          "Done": "Done",
          "Rate this app": "Rate this app",
          "Rating Content":
              "You like this app ? Then take a little bit of your time to leave a rating :",
          "Notification Title": "Notification Title",
          "Delete!": "Delete !",
          "Sure Delete": "Are you sure ?",
          "WhatsApp": "WhatsApp",
          "Text Message": "Text Message",
          "Add Number": "Add Number",
          "Repeat": "Repeat",
          "Date": "Date",
          "Time": "Time",
          "Please enter title": "Please enter notification title",
          "Please enter number": "Please enter mobile number",
          "Please enter name": "Please enter name",
          "Daily": "Daily",
          "Never": "Never",
          "Weekly": "Weekly",
          "Monthly": "Monthly",
          "Yearly": "Yearly",
          "Rate Us": "Rate Us",
          "Share App": "Share App",
          "Help": "Help",
          "More App": "More App",
          "Privacy Policy": "Privacy Policy",
          "Terms of use": "Terms of use",
          "secs ago": "secs ago",
          "mins ago": "mins ago",
          "hour ago": "hour ago",
          "day ago": "day ago",
        },
        "es-ES": {
          "Ok": "OK",
          "Select language": "Seleccione el idioma",
          "Choose Language": "Elige lengua",
          "secs ago": "hace segundos",
          "mins ago": "hace minutos",
          "hour ago": "hace una hora",
          "day ago": "hace un dia",
          "Keyboard": "Teclado",
          "Recent": "Reciente",
          "Schedule": "Calendario",
          "Setting": "Ajuste",
          "Add Name": "Añadir nombre",
          "Add Message": "Agregar mensaje",
          "Enter Name": "Entra mamá",
          "Enter Message": "Ingresar mensaje",
          "No Recent": "No tienes datos recientes",
          "Add Recent": "Añadir datos recientes ahora",
          "No Message": "Sin mensaje",
          "No Schedule":
              "Aún no ha programado un mensaje. Para recordarle la hora programada, le enviaremos una notificación.",
          "Add Schedule": "Programar ahora",
          "Yes": "Sí",
          "No": "No",
          "Cancel": "Cancelar",
          "Done": "Hecho",
          "Rate this app": "Califica esta aplicación",
          "Rating Content":
              "¿Te gusta esta aplicación? Entonces tómate un poco de tu tiempo para dejar una calificación :",
          "Notification Title": "Título de la notificación",
          "Delete!": "Borrar !",
          "Sure Delete": "Está seguro ?",
          "WhatsApp": "WhatsApp",
          "Text Message": "Mensaje de texto",
          "Add Number": "Añade un número",
          "Repeat": "Repetir",
          "Date": "Fecha",
          "Time": "Tiempo",
          "Please enter title":
              "Por favor ingrese el título de la notificación",
          "Please enter number": "Por favor, introduzca el número de móvil",
          "Please enter name": "Por favor ingrese el nombre",
          "Daily": "Diariamente",
          "Never": "Nunca",
          "Weekly": "Semanalmente",
          "Monthly": "Mensual",
          "Yearly": "Anual",
          "Rate Us": "Nos califica",
          "Share App": "Compartir aplicación",
          "Help": "Ayuda",
          "More App": "Más aplicaciones",
          "Privacy Policy": "Política de privacidad",
          "Terms of use": "Términos de Uso",
        },
        "hi_IN": {
          "Ok": "ठीक",
          "Select language": "भाषा का चयन करें",
          "Choose Language": "भाषा चुनें",
          "secs ago": "सेकंड पहले",
          "mins ago": "मिनट पहले",
          "hour ago": "घंटेभर पहले",
          "day ago": "दिन पहले",
          "Keyboard": "कीबोर्ड",
          "Recent": "हालिया",
          "Schedule": "अनुसूची",
          "Setting": "स्थापना",
          "Add Name": "नाम जोड़ें",
          "Add Message": "संदेश जोड़ें",
          "Enter Name": "मैम दर्ज करें",
          "Enter Message": "संदेश दर्ज करें",
          "No Recent": "आपके पास हाल का कोई डेटा नहीं है",
          "Add Recent": "हाल ही का डेटा अभी जोड़ें",
          "No Message": "कोई सन्देश नहीं",
          "No Schedule":
              "आपने अभी तक कोई संदेश शेड्यूल नहीं किया है। निर्धारित समय पर याद दिलाने के लिए हम एक सूचना भेजेंगे।",
          "Add Schedule": "अभी शेड्यूल करें",
          "Yes": "हाँ",
          "No": "नहीं",
          "Cancel": "रद्द करना",
          "Done": "पूर्ण",
          "Rate this app": "इस ऐप्लिकेशन को रेट करें",
          "Rating Content":
              "आपको यह ऐप पसंद है? फिर रेटिंग छोड़ने के लिए अपना थोड़ा सा समय लें:",
          "Notification Title": "अधिसूचना शीर्षक",
          "Delete!": "मिटाना !",
          "Sure Delete": "क्या आपको यकीन है ?",
          "WhatsApp": "व्हाट्सएप",
          "Text Message": "पाठ संदेश",
          "Add Number": "संख्या जोड़ें",
          "Repeat": "दोहराना",
          "Date": "दिनांक",
          "Time": "समय",
          "Please enter title": "कृपया अधिसूचना शीर्षक दर्ज करें",
          "Please enter number": "कृपया मोबाइल नंबर दर्ज करें",
          "Please enter name": "कृपया नाम दर्ज करें",
          "Daily": "रोज",
          "Never": "कभी नहीँ",
          "Weekly": "साप्ताहिक",
          "Monthly": "महीने के",
          "Yearly": "वार्षिक",
          "Rate Us": "हमें रेटिंग दें",
          "Share App": "ऐप शेयर करें",
          "Help": "मदद करना",
          "More App": "और ज्यादा एप्लीकेशन",
          "Privacy Policy": "गोपनीयता नीति",
          "Terms of use": "उपयोग की शर्तें",
        },
        "ru-RU": {
          "Ok": "Ok",
          "Select language": "Выберите язык",
          "Choose Language": "Выберите язык",
          "secs ago": "сек назад",
          "mins ago": "минут назад",
          "hour ago": "час назад",
          "day ago": "день назад",
          "Keyboard": "Клавиатура",
          "Recent": "Недавний",
          "Schedule": "Расписание",
          "Setting": "Параметр",
          "Add Name": "Добавить имя",
          "Add Message": "Добавить сообщение",
          "Enter Name": "Войдите маме",
          "Enter Message": "Введите сообщение",
          "No Recent": "У вас нет свежих данных",
          "Add Recent": "Добавить последние данные сейчас",
          "No Message": "Нет сообщений",
          "No Schedule":
              "Вы еще не запланировали сообщение. Чтобы напомнить в назначенное время, мы отправим уведомление.",
          "Add Schedule": "Запланировать сейчас",
          "Yes": "Да",
          "No": "Нет",
          "Cancel": "Отмена",
          "Done": "Сделанный",
          "Rate this app": "Оцени это приложение",
          "Rating Content":
              "Вам нравится это приложение? Тогда потратьте немного времени, чтобы оставить оценку:",
          "Notification Title": "Заголовок уведомления",
          "Delete!": "Удалить !",
          "Sure Delete": "Ты уверен ?",
          "WhatsApp": "ВатсАпп",
          "Text Message": "Текстовое сообщение",
          "Add Number": "Добавить число",
          "Repeat": "Повторение",
          "Date": "Свидание",
          "Time": "Время",
          "Please enter title": "Пожалуйста, введите заголовок уведомления",
          "Please enter number":
              "Пожалуйста, введите номер мобильного телефона",
          "Please enter name": "Пожалуйста, введите имя",
          "Daily": "Повседневная",
          "Never": "Никогда",
          "Weekly": "Еженедельно",
          "Monthly": "Ежемесячно",
          "Yearly": "Ежегодно",
          "Rate Us": "Оцените нас",
          "Share App": "Поделиться приложением",
          "Help": "Помощь",
          "More App": "Больше приложений",
          "Privacy Policy": "Политика конфиденциальности",
          "Terms of use": "Условия эксплуатации",
        },
        "fr-FR": {
          "Ok": "D'accord",
          "Select language": "Choisir la langue",
          "Choose Language": "Choisissez la langue",
          "hour ago": "Une heure avant",
          "day ago": "il y a un jour",
          "Keyboard": "Clavier",
          "Recent": "Récent",
          "Schedule": "Programme",
          "Setting": "Paramètre",
          "Add Name": "Ajouter un nom",
          "Add Message": "Ajouter un message",
          "Enter Name": "Entrez maman",
          "Enter Message": "Saisir un message",
          "No Recent": "Vous n'avez pas de données récentes",
          "Add Recent": "Ajouter des données récentes maintenant",
          "No Message": "Pas de message",
          "No Schedule":
              "Vous n'avez pas encore programmé de message. Pour vous rappeler à l'heure prévue, nous vous enverrons une notification.",
          "Add Schedule": "Planifier maintenant",
          "Yes": "Oui",
          "No": "Non",
          "Cancel": "Annuler",
          "Done": "Fait",
          "Rate this app": "Évaluer l'application",
          "Rating Content":
              "Vous aimez cette appli ? Alors prenez un peu de votre temps pour laisser une note :",
          "Notification Title": "Titre de la notification",
          "Delete!": "Effacer !",
          "Sure Delete": "Êtes-vous sûr ?",
          "WhatsApp": "WhatsApp",
          "Text Message": "Message texte",
          "Add Number": "Ajouter un numéro",
          "Repeat": "Répéter",
          "Date": "Date",
          "Time": "Temps",
          "Please enter title": "Veuillez saisir le titre de la notification",
          "Please enter number":
              "Veuillez entrer le numéro de téléphone portable",
          "Please enter name": "Veuillez entrer le nom",
          "Daily": "Du quotidien",
          "Never": "Jamais",
          "Weekly": "Hebdomadaire",
          "Monthly": "Mensuel",
          "Yearly": "Annuel",
          "Rate Us": "Évaluez nous",
          "Share App": "Partager l'application",
          "Help": "Aider",
          "More App": "Plus d'application",
          "Privacy Policy": "Politique de confidentialité",
          "Terms of use": "Conditions d'utilisation",
        },
        "de-DE": {
          "Ok": "OK",
          "Select language": "Sprache auswählen",
          "Choose Language": "Sprache wählen",
          "hour ago": "vor einer Stunde",
          "day ago": "vor einem Tag",
          "Keyboard": "Klaviatur",
          "Recent": "Jüngste",
          "Schedule": "Zeitlicher Ablauf",
          "Setting": "Einstellung",
          "Add Name": "Name hinzufügen",
          "Add Message": "Nachricht hinzufügen",
          "Enter Name": "Mama eingeben",
          "Enter Message": "Nachricht eingeben",
          "No Recent": "Sie haben keine aktuellen Daten",
          "Add Recent": "Neueste Daten jetzt hinzufügen",
          "No Message": "Keine Nachricht",
          "No Schedule":
              "Sie haben noch keine Nachricht geplant. Zur Erinnerung an die geplante Zeit senden wir eine Benachrichtigung.",
          "Add Schedule": "Jetzt planen",
          "Yes": "Ja",
          "No": "Nein",
          "Cancel": "Absagen",
          "Done": "Fertig",
          "Rate this app": "Bewerte diese App",
          "Rating Content":
              "Gefällt dir diese App? Dann nimm dir ein wenig Zeit, um eine Bewertung abzugeben :",
          "Notification Title": "Titel der Benachrichtigung",
          "Delete!": "Löschen !",
          "Sure Delete": "Bist du dir sicher ?",
          "WhatsApp": "WhatsApp",
          "Text Message": "Textnachricht",
          "Add Number": "Nummer hinzufügen",
          "Repeat": "Wiederholen",
          "Date": "Datum",
          "Time": "Zeit",
          "Please enter title": "Bitte Benachrichtigungstitel eingeben",
          "Please enter number": "Bitte Handynummer eingeben",
          "Please enter name": "Bitte Namen eingeben",
          "Daily": "Täglich",
          "Never": "Niemals",
          "Weekly": "Wöchentlich",
          "Monthly": "Monatlich",
          "Yearly": "Jährlich",
          "Rate Us": "Bewerten Sie uns",
          "Share App": "App teilen",
          "Help": "Hilfe",
          "More App": "Mehr App",
          "Privacy Policy": "Datenschutz-Bestimmungen",
          "Terms of use": "Nutzungsbedingungen",
        },
        "pt-PT": {
          "Ok": "OK",
          "Select language": "Selecione o idioma",
          "Choose Language": "Escolha o seu idioma",
          "secs ago": "segundos atrás",
          "mins ago": "minutos atrás",
          "hour ago": "hora atrás",
          "day ago": "dia atrás",
          "Keyboard": "Teclado",
          "Recent": "Recente",
          "Schedule": "Cronograma",
          "Setting": "Contexto",
          "Add Name": "Adicionar nome",
          "Add Message": "Adicionar mensagem",
          "Enter Name": "Entra mãe",
          "Enter Message": "Digite a mensagem",
          "No Recent": "Você não tem dados recentes",
          "Add Recent": "Adicionar dados recentes agora",
          "No Message": "Nenhuma mensagem",
          "No Schedule":
              "Você ainda não agendou uma mensagem. Para lembrar no horário agendado, enviaremos uma notificação.",
          "Add Schedule": "Agendar agora",
          "Yes": "Sim",
          "No": "Não",
          "Cancel": "Cancelar",
          "Done": "Feito",
          "Rate this app": "Avalie este aplicativo",
          "Rating Content":
              "Você gostou deste aplicativo? Então reserve um pouco do seu tempo para deixar uma avaliação :",
          "Notification Title": "Título da notificação",
          "Delete!": "Excluir!",
          "Sure Delete": "Tem certeza ?",
          "WhatsApp": "Whatsapp",
          "Text Message": "Mensagem de texto",
          "Add Number": "Adicionar número",
          "Repeat": "Repetir",
          "Date": "Encontro",
          "Time": "Tempo",
          "Please enter title": "Por favor, insira o título da notificação",
          "Please enter number": "Por favor, digite o número do celular",
          "Please enter name": "Por favor, digite o nome",
          "Daily": "Diário",
          "Never": "Nunca",
          "Weekly": "Semanalmente",
          "Monthly": "Por mês",
          "Yearly": "Anual",
          "Rate Us": "Nos avalie",
          "Share App": "Compartilhe o aplicativo",
          "Help": "Ajuda",
          "More App": "Mais aplicações",
          "Privacy Policy": "Política de Privacidade",
          "Terms of use": "Termos de uso",
        },
        "it-IT": {
          "Ok": "Ok",
          "Select language": "Seleziona la lingua",
          "Choose Language": "Scegli la lingua",
          "secs ago": "secondi fa",
          "mins ago": "minuti fa",
          "hour ago": "un'ora fa",
          "day ago": "giorno fa",
          "Keyboard": "Tastiera del computer",
          "Recent": "Recente",
          "Schedule": "Programma",
          "Setting": "Ambientazione",
          "Add Name": "Aggiungi nome",
          "Add Message": "Aggiungi un messaggio",
          "Enter Name": "Entra mamma",
          "Enter Message": "Inserisci messaggio",
          "No Recent": "Non hai dati recenti",
          "Add Recent": "Aggiungi dati recenti ora",
          "No Message": "Nessun messaggio",
          "No Schedule":
              "Non hai ancora programmato un messaggio. Per ricordare l'orario programmato invieremo una notifica.",
          "Add Schedule": "Programma ora",
          "Yes": "Sì",
          "No": "No",
          "Cancel": "Annulla",
          "Done": "Fatto",
          "Rate this app": "Valuta questa applicazione",
          "Rating Content":
              "Ti piace questa app? Allora prenditi un po' del tuo tempo per lasciare una valutazione :",
          "Notification Title": "Titolo della notifica",
          "Delete!": "Elimina !",
          "Sure Delete": "Sei sicuro ?",
          "WhatsApp": "WhatsApp",
          "Text Message": "Messaggio testuale",
          "Add Number": "Aggiungi numero",
          "Repeat": "Ripetere",
          "Date": "Data",
          "Time": "Volta",
          "Please enter title": "Inserisci il titolo della notifica",
          "Please enter number": "Inserisci numero di cellulare",
          "Please enter name": "Inserisci il nome",
          "Daily": "Quotidiano",
          "Never": "Mai",
          "Weekly": "Settimanalmente",
          "Monthly": "Mensile",
          "Yearly": "Annuale",
          "Rate Us": "Votaci",
          "Share App": "Condividi app",
          "Help": "Aiuto",
          "More App": "Più applicazioni",
          "Privacy Policy": "Politica sulla riservatezza",
          "Terms of use": "Termini di utilizzo",
        },
      };
}
